export const defaultSettings = {
  startWeight: 231.9,
  targetWeight: 208,
  startBodyFat: 24.3,
  targetBodyFat: 15,
  defaultBmr: 2085,
  deadline: '2026-06-13',
  bfLossRate: 0.75,
  startDate: '2026-03-16',
  targetMode: 'date'
};

export const state = {
  user: null,
  data: null,
  activeTab: 'today',
  saving: false,
  healthData: [],
  showSettings: false,
  selectedEditDate: null,
  crmFilter: 'all',
  crmExpanded: null,
  crmDatePicker: null,
  calendarYear: new Date().getFullYear(),
  calendarMonth: new Date().getMonth(),
  theme: localStorage.getItem('tjm_theme') || 'dark',
  crmSoldModal: null,
  retentionModal: false,
  retentionExpanded: false,
  retentionFeelings: null,
  retentionEditingDate: null,
  retentionEditDraft: null,
  retentionViewDay: null,
  crmScrollDate: null,
  vaultStage: 'Raw',
  vaultCapturing: false,
  vaultExpanded: null,
  vaultVAOn: false,
  weekPlanModal: null,
  weekPlanObjPanelOpen: false,
  weekPlanDraft: {},
  dayPlannerOpen: false,
  dayPlannerDay: null,
  dayPlannerDraft: null,
  dayPlannerWeekOffset: 0,
  dayPlannerStreamForm: false,
  dayPlannerStreamDraft: null,
  weekObjEditing: null,
  weekBatchStepCache: [],
  challengeSetupOpen: false,
  timePickerOpen: null,
  identityEditing: false,
  identityDraft: {},
  missionEditingIdx: null,
  missionDraft: {},
  batchEditing: null,
  batchDraft: {},
  batchAdding: false,
  stepConfirm: null,
  editBatchStepIdx: 0,
  batchViewStep: {},
  nottsGoalEditing: false,
  nottsGoalDraft: '',
  monthTargetsOpen: false,
  pastDaysOpen: false,
  pastDayEditing: null,
  objModalDate: null,
  taskDeleteConfirm: null,  // { fk, ti, text } — set when user taps remove on a draft task
  reminderDeleteConfirm: null,  // { id, source: 'active' | 'archived' } — set when user taps ✕ on a reminder
  remindersArchiveOpen: false,
};
